# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '\u6821\u533a\u8868',
                'verbose_name_plural': '\u6821\u533a\u8868',
            },
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='\u5b66\u671f')),
                ('class_type', models.SmallIntegerField(choices=[(0, '\u7ebf\u4e0b'), (1, '\u7f51\u7edc')])),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u5f00\u73ed\u65e5\u671f')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Branch')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u8868',
                'verbose_name_plural': '\u73ed\u7ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('period', models.PositiveSmallIntegerField(verbose_name='\u8bfe\u7a0b\u5468\u671f')),
                ('outline', models.TextField()),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8868',
                'verbose_name_plural': '\u8bfe\u7a0b\u8868',
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.PositiveSmallIntegerField(verbose_name='\u8bfe\u7a0b\u53f7')),
                ('has_homework', models.BooleanField(default=True)),
                ('homework_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4f5c\u4e1a\u6807\u9898')),
                ('homework_content', models.TextField(blank=True, null=True, verbose_name='\u4f5c\u4e1a\u5185\u5bb9')),
                ('out_line', models.TextField(verbose_name='\u8bfe\u7a0b\u5927\u7eb2')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u8bfe\u7a0b\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5ba2\u6237\u59d3\u540d')),
                ('qq', models.CharField(max_length=64, unique=True, verbose_name='\u5ba2\u6237QQ')),
                ('qq_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='QQ\u6635\u79f0')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('source', models.SmallIntegerField(choices=[(0, '\u8f6c\u4ecb\u7ecd'), (1, 'qq\u7fa4'), (2, '\u5b98\u7f51'), (3, '\u767e\u5ea6\u63a8\u5e7f'), (4, '51CTO'), (5, '\u77e5\u4e4e'), (6, '\u7ebf\u4e0b\u4f20\u5355')], verbose_name='\u5ba2\u6237\u6765\u6e90')),
                ('referral_from', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8f6c\u4ecb\u7ecd\u4eba\u8054\u7cfb\u65b9\u5f0f')),
                ('consult_content', models.TextField(verbose_name='\u54a8\u8be2\u5185\u5bb9\u8be6\u60c5')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u54a8\u8be2\u65f6\u95f4')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u8ddf\u8fdb\u6982\u51b5')),
                ('consult_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='\u54a8\u8be2\u8bfe\u7a0b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u8868',
                'verbose_name_plural': '\u5ba2\u6237\u8868',
            },
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8ddf\u8fdb\u5185\u5bb9')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('intention', models.SmallIntegerField(choices=[(0, '\u4e24\u5468\u5185\u62a5\u540d'), (1, '\u4e00\u4e2a\u6708\u5185\u62a5\u540d'), (2, '\u6682\u65e0\u62a5\u540d\u8ba1\u5212')])),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u8ddf\u8fdb\u8868',
                'verbose_name_plural': '\u5ba2\u6237\u8ddf\u8fdb\u8868',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_agree', models.BooleanField(default=False, verbose_name='\u5b66\u5458\u662f\u5426\u540c\u610f\u6761\u6b3e')),
                ('contract_approved', models.BooleanField(default=False, verbose_name='\u9500\u552e\u662f\u5426\u5ba1\u6838')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u62a5\u540d\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u62a5\u540d\u8868',
                'verbose_name_plural': '\u62a5\u540d\u8868',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64, unique=True)),
                ('absolute_url', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '\u83dc\u5355\u8868',
                'verbose_name_plural': '\u83dc\u5355\u8868',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='\u7f34\u8d39\u6570\u989d')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u7f34\u8d39\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u7f34\u8d39\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, unique=True)),
                ('show_menu', models.ManyToManyField(blank=True, to='crm.Menu')),
            ],
            options={
                'verbose_name': '\u89d2\u8272\u8868',
                'verbose_name_plural': '\u89d2\u8272\u8868',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.SmallIntegerField(choices=[(0, '\u6b63\u5e38\u51fa\u52e4'), (1, '\u8fdf\u5230'), (2, '\u7f3a\u52e4')], default=0)),
                ('score', models.SmallIntegerField(choices=[(100, 'S'), (95, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (75, 'C+'), (70, 'C'), (65, 'D+'), (60, 'D'), (0, 'E')], default=60)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Enrollment')),
            ],
            options={
                'verbose_name': '\u5b66\u4e60\u60c5\u51b5\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u5b66\u4e60\u60c5\u51b5\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '\u6807\u7b7e\u8868',
                'verbose_name_plural': '\u6807\u7b7e\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('number', models.CharField(max_length=32, verbose_name='\u5de5\u53f7')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Role')),
            ],
            options={
                'verbose_name': '\u8d26\u6237\u8868',
                'verbose_name_plural': '\u8d26\u6237\u8868',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u6240\u62a5\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u9500\u552e'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u4ece\u5c5e\u9500\u552e'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.ManyToManyField(blank=True, to='crm.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(to='crm.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('customer', 'class_enrolled')]),
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together=set([('from_class', 'day_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('branch', 'course', 'semester')]),
        ),
    ]
